services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: alumni_back_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alumni
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5441:5432"

  app:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/alumni_back_db
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: alumni
      QUARKUS_FLYWAY_MIGRATE_AT_START: true
    ports:
      - "8080:8080"

  kafkaservice:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,EXTERNAL://:9093,CONTROLLER://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafkaservice:9092,EXTERNAL://localhost:9093,CONTROLLER://kafkaservice:9094"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafkaservice:9094"
      KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/data"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami/kafka/data


volumes:
  db_data:
  kafka_data: 