ALTER TABLE api_base
    ALTER COLUMN facebook_url TYPE VARCHAR(300),
    ALTER COLUMN linkedin_url TYPE VARCHAR(300);

ALTER TABLE faculty
    ALTER COLUMN faculty_name TYPE VARCHAR(100);

CREATE TABLE degree (
                         degree_id SERIAL PRIMARY KEY,
                         degree VARCHAR(100) NOT NULL
);

CREATE TABLE speciality (
                              id SERIAL PRIMARY KEY,
                              speciality VARCHAR(100) NOT NULL
);

ALTER TABLE faculty ALTER COLUMN faculty_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE alumni DROP COLUMN degree;

ALTER TABLE alumni ADD COLUMN degree_id INT REFERENCES degree(degree_id);

ALTER TABLE alumni_groups DROP COLUMN speciality;

ALTER TABLE alumni_groups ADD COLUMN speciality_id INT REFERENCES speciality(id);

CREATE INDEX idx_alumni_api_base_id ON alumni(api_base_id);
CREATE INDEX idx_alumni_degree_id ON alumni(degree_id);
CREATE INDEX idx_alumni_details_faculty_id ON alumni_details(faculty_id);
CREATE INDEX idx_alumni_groups_speciality_id ON alumni_groups(speciality_id);
