## CI build workflow for Quarkus with Docker Compose (services first, build with your Maven setup)

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Start Postgres first
      - name: Start Postgres
        run: docker compose -f ./docker/docker-compose.yml up -d db

      # Wait for Postgres to be ready (5 seconds)
      - name: Wait for Postgres
        run: |
          echo "Waiting 5 seconds for Postgres..."
          sleep 5

      # Start Kafka
      - name: Start Kafka
        run: docker compose -f ./docker/docker-compose.yml up -d kafkaservice

      # Wait for Kafka to be ready (15 seconds)
      - name: Wait for Kafka
        run: |
          echo "Waiting 15 seconds for Kafka..."
          sleep 15

      # Start the app container
      - name: Start App container
        run: docker compose -f ./docker/docker-compose.yml up -d app

      # Wait a few seconds for the app to initialize
      - name: Wait for App
        run: |
          echo "Waiting 5 seconds for App to initialize..."
          sleep 5

      # --- YOUR ORIGINAL JAVA + MAVEN LOGIC ---
      # Set up Java and Maven auth for GitHub Packages
      - name: Set up Java and Maven auth for GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
          token: ${{ secrets.GH_PACKAGES_TOKEN }}

      # Configure Maven settings.xml for GitHub Packages
      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>OleksPorokhnia</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # Build Quarkus project (integration tests run inside the app container)
      - name: Build Quarkus project inside container
        run: docker compose exec app ./mvnw verify -B
