name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Java 21 with Maven cache and GitHub Packages auth
      - name: Set up Java and Maven auth for GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: github
          server-username: OleksPorokhnia
          server-password: ${{ secrets.GH_PACKAGES_TOKEN }}

      # Verify Maven can fetch dependencies and build the project
      - name: Build with Maven
        run: ./mvnw clean verify -B
