name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Set up Java and Maven auth for GitHub Packages
      - name: Set up Java and Maven auth for GitHub Packages
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}
          token: ${{ secrets.GH_PACKAGES_TOKEN }}

      # 3. Configure Maven settings.xml
      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>OleksPorokhnia</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 4. Start Postgres and Kafka
      - name: Start Postgres and Kafka
        run: |
          docker compose -f ./src/main/docker/docker-compose.yml up -d db kafkaservice
          echo "Waiting for Postgres (5s)..."
          sleep 10
          echo "Waiting for Kafka (15s)..."
          sleep 15

      # 5. Build the Quarkus project (including tests)
      - name: Build Quarkus app with tests
        run: ./mvnw verify -B

